"""add_cascade_delete_for_chatter_relations

Revision ID: a6d07adc10ea
Revises: 0002
Create Date: 2025-10-24 09:25:31.816948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6d07adc10ea'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('offenses_chatter_id_fkey'), 'offenses', type_='foreignkey')
    op.create_foreign_key(None, 'offenses', 'chatters', ['chatter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('performance_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('performance_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('performance_daily_chatter_id_fkey'), 'performance_daily', type_='foreignkey')
    op.create_foreign_key(None, 'performance_daily', 'chatters', ['chatter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('rankings_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('rankings_daily_chatter_id_fkey'), 'rankings_daily', type_='foreignkey')
    op.create_foreign_key(None, 'rankings_daily', 'chatters', ['chatter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.alter_column('saved_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('shifts_chatter_id_fkey'), 'shifts', type_='foreignkey')
    op.create_foreign_key(None, 'shifts', 'chatters', ['chatter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.create_foreign_key(op.f('shifts_chatter_id_fkey'), 'shifts', 'chatters', ['chatter_id'], ['id'])
    op.alter_column('saved_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'rankings_daily', type_='foreignkey')
    op.create_foreign_key(op.f('rankings_daily_chatter_id_fkey'), 'rankings_daily', 'chatters', ['chatter_id'], ['id'])
    op.alter_column('rankings_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'performance_daily', type_='foreignkey')
    op.create_foreign_key(op.f('performance_daily_chatter_id_fkey'), 'performance_daily', 'chatters', ['chatter_id'], ['id'])
    op.alter_column('performance_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('performance_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'offenses', type_='foreignkey')
    op.create_foreign_key(op.f('offenses_chatter_id_fkey'), 'offenses', 'chatters', ['chatter_id'], ['id'])
    op.alter_column('audit_logs', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attachments', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
